source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'

pod 'FLKAutoLayout', '~> 0.2'

inhibit_all_warnings!

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Developer'
    end
  end
end
