source 'https://github.com/CocoaPods/Specs.git'

platform :osx, '10.10'

#pod 'AppMap', :git => 'https://github.com/nickbolton/appmapp-runtime.git', :branch=>'master'

inhibit_all_warnings!

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGN_IDENTITY'] = 'iPhone Developer'
    end
  end
end
